# prod-team-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-team-reconciler-role
  namespace: dev-team
rules:
  - apiGroups: ["", "apps", "batch"]
    resources: ["services", "pods", "deployments", "replicasets", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-team-reconciler-rolebinding
  namespace: dev-team
subjects:
  - kind: ServiceAccount
    name: ns-reconciler-prod-team-reposync-dev-13
    namespace: config-management-system
roleRef:
  kind: Role
  name: dev-team-reconciler-role
  apiGroup: rbac.authorization.k8s.io
