apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: root-sync
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/RajivBB/kpt-test.git
    branch: main
    dir: gitops-root-repo-with-policy/cluster/kind-hub/
    auth: token
    secretRef:
      name: git-creds
